<?php

error_reporting(E_ALL);
ini_set('display_errors','On');
header('Content-Type: text/plain');

require_once('../base/TokenPay.php');

// BELOW WOULD BE POPULATED BY A FORM POST, OF COURSE
// Read how to do a 2CO token-based charge form: 
// https://www.2checkout.com/documentation/payment-api/create-token
$sToken = 'N5555llZjYtMjFlOS44ZDJlLTlkZjktMGIyNjg3ZDkwN2Nh'; // uniqely generated by 2co.js - CHANGE ME

$sTCOPrivateKey = '44F8C844-5555-4744-9E44-760A21B1C344'; // CHANGE ME

$sSellerID = '941555566'; // CHANGE ME

$sMerchantOrderID = uniqid();

$sSKU = 'ACME-WIDGET-00001';

$sName = 'John Doe';
$sStreet1 = '100 Main Street';
$sStreet2 = 'Apt A';
$sCity = 'New York';
$sState = 'NY';
$sZip = '00000';
$sCountry = 'US';
$sPhone = '000-000-0000';
$sEmail = 'test@example.com';

$sSName = 'John Doe';
$sSStreet1 = '100 Main Street';
$sSStreet2 = 'Apt A';
$sSCity = 'New York';
$sSState = 'NY';
$sSZip = '00000';
$sSCountry = 'US';
$sSPhone = '000-000-0000';

// NOW PREPARE TO CHARGE
$sPrice = '100.50';
$sCurrency = 'USD';
$sDesc = "$sSKU : $sName : $sEmail : $sZip";

// NOW CHARGE
$o = TokenPay::createGateway('2checkout');
$o->setAPIKey($sTCOPrivateKey);
$o->setSellerID($sSellerID); // note this is unique to 2CO
$o->setMerchantOrderID($sMerchantOrderID); // note this is unique to 2CO
$o->setDebugMode(TRUE); // whether to send output of sending and receiving to the screen
$o->setTestMode(TRUE);
$o->setBilling(array(
	'billingName' => $sName,
	'billingAddress1' => $sStreet1,
	'billingAddress2' => $sStreet2,
	'billingCity' => $sCity,
	'billingState' => $sState,
	'billingPostcode' => $sZip,
	'billingCountry' => $sCountry,
	'billingPhone' => $sPhone,
	'email' => $sEmail
));
$o->setShipping(array(
	'shippingName' => $sSName,
	'shippingAddress1' => $sSStreet1,
	'shippingAddress2' => $sSStreet2,
	'shippingCity' => $sSCity,
	'shippingState' => $sSState,
	'shippingPostcode' => $sSZip,
	'shippingCountry' => $sSCountry,
	'shippingPhone' => $sSPhone
));
$o->setCharge(array(
	'amount' => $sPrice,
	'currency' => $sCurrency,
	'token' => $sToken,
	'description' => $sDesc
));
$oResponse = $o->chargeCard(); // HERE WE GO!
if ($oResponse->isSuccess) {
	$sTransID = $oResponse->TransID;
	die('SUCCESS: ' . $sTransID);
} else {
	$sError = $oResponse->FailMessage;
	$nError = $oResponse->FailCode;
	die('FAIL: ' . $sError . ' (' . $nError . ')');
}

