<?php

error_reporting(E_ALL);
ini_set('display_errors','On');
header('Content-Type: text/plain');

require_once('../base/TokenPay.php');

// BELOW WOULD BE POPULATED BY A FORM POST, OF COURSE
// See our braintree-form for an example because this client token process may be confusing when reading their docs alone.
$sToken = @ $_POST['token']; // uniquely generated by braintree.js
//echo "\n\nTOKEN = $sToken";

$sBraintreePublicKey = '8m555559wknrxs88'; // CHANGE ME
$sBraintreePrivateKey = '287555594aa5f1fe0214fe57aa353111'; // CHANGE ME
$sBraintreeMerchantID = 'z355557wz4spkzzw'; // CHANGE ME

$sSKU = 'ACME-WIDGET-00001';

$sName = 'John Doe';
$sStreet1 = '100 Main Street';
$sStreet2 = 'Apt A';
$sCity = 'New York';
$sState = 'NY';
$sZip = '00000';
$sCountry = 'US';
$sPhone = '000-000-0000';
$sEmail = 'test@example.com';

$sSName = 'John Doe';
$sSStreet1 = '100 Main Street';
$sSStreet2 = 'Apt A';
$sSCity = 'New York';
$sSState = 'NY';
$sSZip = '00000';
$sSCountry = 'US';
$sSPhone = '000-000-0000';

// NOW PREPARE TO CHARGE
$sPrice = '100.50';
$sCurrency = 'USD';
$sDesc = "$sSKU : $sName : $sEmail : $sZip";

// NOW CHARGE
$o = TokenPay::createGateway('braintree');
$o->setPrivateKey($sBraintreePrivateKey); // could also use setAPIKey()
$o->setPublicKey($sBraintreePublicKey); // unique to Braintree
$o->setMerchantID($sBraintreeMerchantID); // unique to Braintree
$o->setDebugMode(FALSE); // whether to send output of sending and receiving to the screen
$o->setTestMode(TRUE); // use the sandbox
$o->setBilling(array(
	'billingName' => $sName,
	'billingAddress1' => $sStreet1,
	'billingAddress2' => $sStreet2,
	'billingCity' => $sCity,
	'billingState' => $sState,
	'billingPostcode' => $sZip,
	'billingCountry' => $sCountry,
	'billingPhone' => $sPhone,
	'email' => $sEmail
));
$o->setShipping(array(
	'shippingName' => $sSName,
	'shippingAddress1' => $sSStreet1,
	'shippingAddress2' => $sSStreet2,
	'shippingCity' => $sSCity,
	'shippingState' => $sSState,
	'shippingPostcode' => $sSZip,
	'shippingCountry' => $sSCountry,
	'shippingPhone' => $sSPhone
));
$o->setCharge(array( // note no currency because it's specified in the Braintree dashboard
	'amount' => $sPrice,
	'token' => $sToken,
	'description' => $sDesc // WARNING! See [*] below.
));
$oResponse = $o->chargeCard(); // HERE WE GO!
if ($oResponse->isSuccess) {
	$sTransID = $oResponse->TransID;
	die('SUCCESS: ' . $sTransID);
} else {
	$sError = $oResponse->FailMessage;
	$nError = $oResponse->FailCode;
	die('FAIL: ' . $sError . ' (' . $nError . ')');
}

/*

[*] Braintree doesn't have a description field on transactions. Instead, you have two choices:

(a) leave this parameter out
(b) create a custom field in the dashboard called "custom_description" (both API and display name versions are fine).

If you chose b, then failure to create that custom description will generate an HTTP response code of 422 from the API.

*/

